<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Supplier;

class SuppliersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $suppliers = [
            [
                'name' => 'Ingram Micro',
                'contact_person' => 'Daniel Foster',
                'email' => 'daniel.foster@ingrammicro.example',
                'phone' => '+1-555-100-0001',
                'website' => 'https://www.ingrammicro.com',
                'address_line_1' => '120 Technology Way',
                'address_line_2' => 'Suite 101',
                'city' => 'Irvine',
                'state' => 'CA',
                'postal_code' => '92612',
                'country' => 'USA',
                'is_active' => true,
            ],
            [
                'name' => 'TD SYNNEX',
                'contact_person' => 'Melissa Grant',
                'email' => 'melissa.grant@tdsynnex.example',
                'phone' => '+1-555-100-0002',
                'website' => 'https://www.tdsynnex.com',
                'address_line_1' => '245 Commerce Drive',
                'address_line_2' => 'Floor 2',
                'city' => 'Fremont',
                'state' => 'CA',
                'postal_code' => '94538',
                'country' => 'USA',
                'is_active' => true,
            ],
            [
                'name' => 'D&H Distributing',
                'contact_person' => 'Anthony Miller',
                'email' => 'anthony.miller@dandh.example',
                'phone' => '+1-555-100-0003',
                'website' => 'https://www.dandh.com',
                'address_line_1' => '88 Distribution Park',
                'address_line_2' => null,
                'city' => 'Harrisburg',
                'state' => 'PA',
                'postal_code' => '17112',
                'country' => 'USA',
                'is_active' => true,
            ],
            [
                'name' => 'ScanSource',
                'contact_person' => 'Rachel Simmons',
                'email' => 'rachel.simmons@scansource.example',
                'phone' => '+1-555-100-0004',
                'website' => 'https://www.scansource.com',
                'address_line_1' => '410 Supply Chain Boulevard',
                'address_line_2' => 'Suite 104',
                'city' => 'Greenville',
                'state' => 'SC',
                'postal_code' => '29615',
                'country' => 'USA',
                'is_active' => true,
            ],
            [
                'name' => 'ASI Corp',
                'contact_person' => 'Kevin Park',
                'email' => 'kevin.park@asicorp.example',
                'phone' => '+1-555-100-0005',
                'website' => 'https://www.asipartner.com',
                'address_line_1' => '930 Enterprise Road',
                'address_line_2' => null,
                'city' => 'Fremont',
                'state' => 'CA',
                'postal_code' => '94538',
                'country' => 'USA',
                'is_active' => true,
            ],
            [
                'name' => 'Ma Labs',
                'contact_person' => 'Steven Wu',
                'email' => 'steven.wu@malabs.example',
                'phone' => '+1-555-100-0006',
                'website' => 'https://www.malabs.com',
                'address_line_1' => '155 Logistics Avenue',
                'address_line_2' => 'Suite 106',
                'city' => 'San Jose',
                'state' => 'CA',
                'postal_code' => '95132',
                'country' => 'USA',
                'is_active' => true,
            ],
            [
                'name' => 'Petra Industries',
                'contact_person' => 'Lauren Hayes',
                'email' => 'lauren.hayes@petra.example',
                'phone' => '+1-555-100-0007',
                'website' => 'https://www.petra.com',
                'address_line_1' => '670 Trade Center Drive',
                'address_line_2' => null,
                'city' => 'Edmond',
                'state' => 'OK',
                'postal_code' => '73013',
                'country' => 'USA',
                'is_active' => true,
            ],
            [
                'name' => 'Westcon-Comstor',
                'contact_person' => 'Marcus Allen',
                'email' => 'marcus.allen@westconcomstor.example',
                'phone' => '+1-555-100-0008',
                'website' => 'https://www.westconcomstor.com',
                'address_line_1' => '52 Channel Partner Lane',
                'address_line_2' => 'Suite 108',
                'city' => 'Tarrytown',
                'state' => 'NY',
                'postal_code' => '10591',
                'country' => 'USA',
                'is_active' => true,
            ],
            [
                'name' => 'Arrow Electronics',
                'contact_person' => 'Nicole Turner',
                'email' => 'nicole.turner@arrow.example',
                'phone' => '+1-555-100-0009',
                'website' => 'https://www.arrow.com',
                'address_line_1' => '300 Business Park Way',
                'address_line_2' => null,
                'city' => 'Centennial',
                'state' => 'CO',
                'postal_code' => '80112',
                'country' => 'USA',
                'is_active' => true,
            ],
            [
                'name' => 'Exertis',
                'contact_person' => 'Oliver Bennett',
                'email' => 'oliver.bennett@exertis.example',
                'phone' => '+44-555-100-0010',
                'website' => 'https://www.exertis.com',
                'address_line_1' => '785 Market Access Road',
                'address_line_2' => 'Unit 10',
                'city' => 'Basingstoke',
                'state' => null,
                'postal_code' => 'RG24 8WA',
                'country' => 'United Kingdom',
                'is_active' => true,
            ],
            [
                'name' => 'Exertis Almo',
                'contact_person' => 'Emily Carter',
                'email' => 'emily.carter@exertisalmo.example',
                'phone' => '+1-555-100-0011',
                'website' => 'https://www.exertisalmo.com',
                'address_line_1' => '640 Solutions Boulevard',
                'address_line_2' => null,
                'city' => 'Philadelphia',
                'state' => 'PA',
                'postal_code' => '19103',
                'country' => 'USA',
                'is_active' => true,
            ],
            [
                'name' => 'BlueStar',
                'contact_person' => 'Jason Reed',
                'email' => 'jason.reed@bluestar.example',
                'phone' => '+1-555-100-0012',
                'website' => 'https://www.bluestarinc.com',
                'address_line_1' => '190 Vendor Plaza',
                'address_line_2' => 'Suite 112',
                'city' => 'Hebron',
                'state' => 'KY',
                'postal_code' => '41048',
                'country' => 'USA',
                'is_active' => true,
            ],
            [
                'name' => 'Climb Channel Solutions',
                'contact_person' => 'Sophia Brooks',
                'email' => 'sophia.brooks@climbcs.example',
                'phone' => '+1-555-100-0013',
                'website' => 'https://www.climbcs.com',
                'address_line_1' => '120 Technology Way',
                'address_line_2' => null,
                'city' => 'Eatontown',
                'state' => 'NJ',
                'postal_code' => '07724',
                'country' => 'USA',
                'is_active' => true,
            ],
            [
                'name' => 'Infinigate',
                'contact_person' => 'Nathan Collins',
                'email' => 'nathan.collins@infinigate.example',
                'phone' => '+41-555-100-0014',
                'website' => 'https://www.infinigate.com',
                'address_line_1' => '245 Commerce Drive',
                'address_line_2' => 'Suite 214',
                'city' => 'Rotkreuz',
                'state' => null,
                'postal_code' => '6343',
                'country' => 'Switzerland',
                'is_active' => true,
            ],
            [
                'name' => 'ALSO',
                'contact_person' => 'Ava Mitchell',
                'email' => 'ava.mitchell@also.example',
                'phone' => '+41-555-100-0015',
                'website' => 'https://www.also.com',
                'address_line_1' => '88 Distribution Park',
                'address_line_2' => null,
                'city' => 'Emmen',
                'state' => null,
                'postal_code' => '6032',
                'country' => 'Switzerland',
                'is_active' => true,
            ],
            [
                'name' => 'Esprinet',
                'contact_person' => 'Giulia Romano',
                'email' => 'giulia.romano@esprinet.example',
                'phone' => '+39-555-100-0016',
                'website' => 'https://www.esprinet.com',
                'address_line_1' => '410 Supply Chain Boulevard',
                'address_line_2' => 'Suite 216',
                'city' => 'Vimercate',
                'state' => null,
                'postal_code' => '20871',
                'country' => 'Italy',
                'is_active' => true,
            ],
            [
                'name' => 'Redington',
                'contact_person' => 'Arjun Mehta',
                'email' => 'arjun.mehta@redington.example',
                'phone' => '+91-555-100-0017',
                'website' => 'https://www.redingtongroup.com',
                'address_line_1' => '930 Enterprise Road',
                'address_line_2' => null,
                'city' => 'Chennai',
                'state' => 'Tamil Nadu',
                'postal_code' => '600091',
                'country' => 'India',
                'is_active' => true,
            ],
            [
                'name' => 'ELKO Group',
                'contact_person' => 'Elina Ozols',
                'email' => 'elina.ozols@elkogroup.example',
                'phone' => '+371-555-100-0018',
                'website' => 'https://www.elkogroup.com',
                'address_line_1' => '155 Logistics Avenue',
                'address_line_2' => 'Suite 218',
                'city' => 'Riga',
                'state' => null,
                'postal_code' => 'LV-1010',
                'country' => 'Latvia',
                'is_active' => true,
            ],
            [
                'name' => 'AB S.A.',
                'contact_person' => 'Piotr Nowak',
                'email' => 'piotr.nowak@absa.example',
                'phone' => '+48-555-100-0019',
                'website' => 'https://www.ab.pl',
                'address_line_1' => '670 Trade Center Drive',
                'address_line_2' => null,
                'city' => 'Magnice',
                'state' => null,
                'postal_code' => '55-040',
                'country' => 'Poland',
                'is_active' => true,
            ],
            [
                'name' => 'MCR',
                'contact_person' => 'Charlotte Davis',
                'email' => 'charlotte.davis@mcr.example',
                'phone' => '+44-555-100-0020',
                'website' => 'https://www.mcr.co.uk',
                'address_line_1' => '52 Channel Partner Lane',
                'address_line_2' => 'Unit 20',
                'city' => 'Basingstoke',
                'state' => null,
                'postal_code' => 'RG24 8UP',
                'country' => 'United Kingdom',
                'is_active' => true,
            ],
            [
                'name' => 'CMS Distribution',
                'contact_person' => 'Ryan Cooper',
                'email' => 'ryan.cooper@cmsdistribution.example',
                'phone' => '+353-555-100-0021',
                'website' => 'https://www.cmsdistribution.com',
                'address_line_1' => '300 Business Park Way',
                'address_line_2' => null,
                'city' => 'Kiltimagh',
                'state' => null,
                'postal_code' => 'F12 XD62',
                'country' => 'Ireland',
                'is_active' => true,
            ],
            [
                'name' => 'Midwich',
                'contact_person' => 'Grace Evans',
                'email' => 'grace.evans@midwich.example',
                'phone' => '+44-555-100-0022',
                'website' => 'https://www.midwich.com',
                'address_line_1' => '785 Market Access Road',
                'address_line_2' => 'Unit 22',
                'city' => 'Diss',
                'state' => null,
                'postal_code' => 'IP22 4GT',
                'country' => 'United Kingdom',
                'is_active' => true,
            ],
            [
                'name' => 'Exclusive Networks',
                'contact_person' => 'Luc Martin',
                'email' => 'luc.martin@exclusivenetworks.example',
                'phone' => '+33-555-100-0023',
                'website' => 'https://www.exclusive-networks.com',
                'address_line_1' => '640 Solutions Boulevard',
                'address_line_2' => null,
                'city' => 'Boulogne-Billancourt',
                'state' => null,
                'postal_code' => '92100',
                'country' => 'France',
                'is_active' => true,
            ],
            [
                'name' => 'Siewert & Kau',
                'contact_person' => 'Liam Turner',
                'email' => 'liam.turner@siewertkau.example',
                'phone' => '+49-555-100-0024',
                'website' => 'https://www.siewert-kau.com',
                'address_line_1' => '190 Vendor Plaza',
                'address_line_2' => 'Building 24',
                'city' => 'Bergheim',
                'state' => null,
                'postal_code' => '50126',
                'country' => 'Germany',
                'is_active' => true,
            ],
            [
                'name' => 'Dicker Data',
                'contact_person' => 'Oliver Hughes',
                'email' => 'oliver.hughes@dickerdata.example',
                'phone' => '+61-555-100-0025',
                'website' => 'https://www.dickerdata.com.au',
                'address_line_1' => '120 Technology Way',
                'address_line_2' => null,
                'city' => 'Kurnell',
                'state' => 'NSW',
                'postal_code' => '2231',
                'country' => 'Australia',
                'is_active' => true,
            ],
            [
                'name' => 'Leader Computers',
                'contact_person' => 'Mia Sanders',
                'email' => 'mia.sanders@leadercomputers.example',
                'phone' => '+61-555-100-0026',
                'website' => 'https://www.leader.com.au',
                'address_line_1' => '245 Commerce Drive',
                'address_line_2' => 'Level 2',
                'city' => 'Adelaide',
                'state' => 'SA',
                'postal_code' => '5000',
                'country' => 'Australia',
                'is_active' => true,
            ],
            [
                'name' => 'Sektor',
                'contact_person' => 'Noah Price',
                'email' => 'noah.price@sektor.example',
                'phone' => '+61-555-100-0027',
                'website' => 'https://www.sektor.com.au',
                'address_line_1' => '88 Distribution Park',
                'address_line_2' => null,
                'city' => 'Melbourne',
                'state' => 'VIC',
                'postal_code' => '3000',
                'country' => 'Australia',
                'is_active' => true,
            ],
            [
                'name' => 'XIT Distribution',
                'contact_person' => 'Ella Murphy',
                'email' => 'ella.murphy@xitdistribution.example',
                'phone' => '+61-555-100-0028',
                'website' => 'https://www.xitdistribution.com',
                'address_line_1' => '410 Supply Chain Boulevard',
                'address_line_2' => 'Suite 228',
                'city' => 'Sydney',
                'state' => 'NSW',
                'postal_code' => '2000',
                'country' => 'Australia',
                'is_active' => true,
            ],
            [
                'name' => 'ASBIS',
                'contact_person' => 'Andreas Costa',
                'email' => 'andreas.costa@asbis.example',
                'phone' => '+357-555-100-0029',
                'website' => 'https://www.asbis.com',
                'address_line_1' => '930 Enterprise Road',
                'address_line_2' => null,
                'city' => 'Limassol',
                'state' => null,
                'postal_code' => '3045',
                'country' => 'Cyprus',
                'is_active' => true,
            ],
            [
                'name' => 'Supertron Electronics',
                'contact_person' => 'Priya Sharma',
                'email' => 'priya.sharma@supertron.example',
                'phone' => '+91-555-100-0030',
                'website' => 'https://www.supertronindia.com',
                'address_line_1' => '155 Logistics Avenue',
                'address_line_2' => 'Suite 230',
                'city' => 'Kolkata',
                'state' => 'West Bengal',
                'postal_code' => '700091',
                'country' => 'India',
                'is_active' => true,
            ],
            [
                'name' => 'Rashi Peripherals',
                'contact_person' => 'Vikram Rao',
                'email' => 'vikram.rao@rashiperipherals.example',
                'phone' => '+91-555-100-0031',
                'website' => 'https://www.rptechindia.com',
                'address_line_1' => '670 Trade Center Drive',
                'address_line_2' => null,
                'city' => 'Mumbai',
                'state' => 'Maharashtra',
                'postal_code' => '400093',
                'country' => 'India',
                'is_active' => true,
            ],
            [
                'name' => 'Savex Technologies',
                'contact_person' => 'Neha Kapoor',
                'email' => 'neha.kapoor@savex.example',
                'phone' => '+91-555-100-0032',
                'website' => 'https://www.savex.in',
                'address_line_1' => '52 Channel Partner Lane',
                'address_line_2' => 'Suite 232',
                'city' => 'Mumbai',
                'state' => 'Maharashtra',
                'postal_code' => '400072',
                'country' => 'India',
                'is_active' => true,
            ],
            [
                'name' => 'Iris Global Services',
                'contact_person' => 'Karan Bhatia',
                'email' => 'karan.bhatia@irisglobal.example',
                'phone' => '+91-555-100-0033',
                'website' => 'https://www.irisglobal.in',
                'address_line_1' => '300 Business Park Way',
                'address_line_2' => null,
                'city' => 'New Delhi',
                'state' => 'Delhi',
                'postal_code' => '110020',
                'country' => 'India',
                'is_active' => true,
            ],
            [
                'name' => 'Compuage Infocom',
                'contact_person' => 'Ananya Desai',
                'email' => 'ananya.desai@compuage.example',
                'phone' => '+91-555-100-0034',
                'website' => 'https://www.compuageindia.com',
                'address_line_1' => '785 Market Access Road',
                'address_line_2' => 'Floor 3',
                'city' => 'Mumbai',
                'state' => 'Maharashtra',
                'postal_code' => '400059',
                'country' => 'India',
                'is_active' => true,
            ],
            [
                'name' => 'VSTECS',
                'contact_person' => 'Chloe Wong',
                'email' => 'chloe.wong@vstecs.example',
                'phone' => '+852-555-100-0035',
                'website' => 'https://www.vstecs.com',
                'address_line_1' => '640 Solutions Boulevard',
                'address_line_2' => null,
                'city' => 'Kwun Tong',
                'state' => null,
                'postal_code' => '999077',
                'country' => 'Hong Kong',
                'is_active' => true,
            ],
            [
                'name' => 'SiS Distribution',
                'contact_person' => 'Ethan Lim',
                'email' => 'ethan.lim@sisdistribution.example',
                'phone' => '+65-555-100-0036',
                'website' => 'https://www.sisdistribution.com.sg',
                'address_line_1' => '190 Vendor Plaza',
                'address_line_2' => 'Unit 36',
                'city' => 'Singapore',
                'state' => null,
                'postal_code' => '608531',
                'country' => 'Singapore',
                'is_active' => true,
            ],
            [
                'name' => 'Pax8',
                'contact_person' => 'Benjamin Ward',
                'email' => 'benjamin.ward@pax8.example',
                'phone' => '+1-555-100-0037',
                'website' => 'https://www.pax8.com',
                'address_line_1' => '120 Technology Way',
                'address_line_2' => null,
                'city' => 'Greenwood Village',
                'state' => 'CO',
                'postal_code' => '80111',
                'country' => 'USA',
                'is_active' => true,
            ],
            [
                'name' => 'Sherweb',
                'contact_person' => 'Lucas Tremblay',
                'email' => 'lucas.tremblay@sherweb.example',
                'phone' => '+1-555-100-0038',
                'website' => 'https://www.sherweb.com',
                'address_line_1' => '245 Commerce Drive',
                'address_line_2' => 'Suite 338',
                'city' => 'Sherbrooke',
                'state' => 'QC',
                'postal_code' => 'J1L 2T9',
                'country' => 'Canada',
                'is_active' => true,
            ],
            [
                'name' => 'Crayon',
                'contact_person' => 'Ingrid Solberg',
                'email' => 'ingrid.solberg@crayon.example',
                'phone' => '+47-555-100-0039',
                'website' => 'https://www.crayon.com',
                'address_line_1' => '88 Distribution Park',
                'address_line_2' => null,
                'city' => 'Oslo',
                'state' => null,
                'postal_code' => '0277',
                'country' => 'Norway',
                'is_active' => true,
            ],
            [
                'name' => 'Softcat',
                'contact_person' => 'James Fletcher',
                'email' => 'james.fletcher@softcat.example',
                'phone' => '+44-555-100-0040',
                'website' => 'https://www.softcat.com',
                'address_line_1' => '410 Supply Chain Boulevard',
                'address_line_2' => 'Floor 4',
                'city' => 'Marlow',
                'state' => null,
                'postal_code' => 'SL7 1YL',
                'country' => 'United Kingdom',
                'is_active' => true,
            ],
            [
                'name' => 'Insight Enterprises',
                'contact_person' => 'Harper Morgan',
                'email' => 'harper.morgan@insight.example',
                'phone' => '+1-555-100-0041',
                'website' => 'https://www.insight.com',
                'address_line_1' => '930 Enterprise Road',
                'address_line_2' => null,
                'city' => 'Chandler',
                'state' => 'AZ',
                'postal_code' => '85286',
                'country' => 'USA',
                'is_active' => true,
            ],
            [
                'name' => 'CDW',
                'contact_person' => 'Samuel Jenkins',
                'email' => 'samuel.jenkins@cdw.example',
                'phone' => '+1-555-100-0042',
                'website' => 'https://www.cdw.com',
                'address_line_1' => '155 Logistics Avenue',
                'address_line_2' => 'Suite 442',
                'city' => 'Vernon Hills',
                'state' => 'IL',
                'postal_code' => '60061',
                'country' => 'USA',
                'is_active' => true,
            ],
            [
                'name' => 'Connection',
                'contact_person' => 'Zoe Richardson',
                'email' => 'zoe.richardson@connection.example',
                'phone' => '+1-555-100-0043',
                'website' => 'https://www.connection.com',
                'address_line_1' => '670 Trade Center Drive',
                'address_line_2' => null,
                'city' => 'Merrimack',
                'state' => 'NH',
                'postal_code' => '03054',
                'country' => 'USA',
                'is_active' => true,
            ],
            [
                'name' => 'Zones',
                'contact_person' => 'David Flores',
                'email' => 'david.flores@zones.example',
                'phone' => '+1-555-100-0044',
                'website' => 'https://www.zones.com',
                'address_line_1' => '52 Channel Partner Lane',
                'address_line_2' => 'Building 44',
                'city' => 'Auburn',
                'state' => 'WA',
                'postal_code' => '98001',
                'country' => 'USA',
                'is_active' => true,
            ],
            [
                'name' => 'SHI International',
                'contact_person' => 'Megan Russell',
                'email' => 'megan.russell@shi.example',
                'phone' => '+1-555-100-0045',
                'website' => 'https://www.shi.com',
                'address_line_1' => '300 Business Park Way',
                'address_line_2' => null,
                'city' => 'Somerset',
                'state' => 'NJ',
                'postal_code' => '08873',
                'country' => 'USA',
                'is_active' => true,
            ],
            [
                'name' => 'Computacenter',
                'contact_person' => 'Callum Scott',
                'email' => 'callum.scott@computacenter.example',
                'phone' => '+44-555-100-0046',
                'website' => 'https://www.computacenter.com',
                'address_line_1' => '785 Market Access Road',
                'address_line_2' => 'Unit 46',
                'city' => 'Hatfield',
                'state' => null,
                'postal_code' => 'AL10 9TW',
                'country' => 'United Kingdom',
                'is_active' => true,
            ],
            [
                'name' => 'Bechtle',
                'contact_person' => 'Hannah Vogel',
                'email' => 'hannah.vogel@bechtle.example',
                'phone' => '+49-555-100-0047',
                'website' => 'https://www.bechtle.com',
                'address_line_1' => '640 Solutions Boulevard',
                'address_line_2' => null,
                'city' => 'Neckarsulm',
                'state' => null,
                'postal_code' => '74172',
                'country' => 'Germany',
                'is_active' => true,
            ],
            [
                'name' => 'CANCOM',
                'contact_person' => 'Jonas Keller',
                'email' => 'jonas.keller@cancom.example',
                'phone' => '+49-555-100-0048',
                'website' => 'https://www.cancom.com',
                'address_line_1' => '190 Vendor Plaza',
                'address_line_2' => 'Suite 448',
                'city' => 'Munich',
                'state' => null,
                'postal_code' => '81677',
                'country' => 'Germany',
                'is_active' => true,
            ],
            [
                'name' => 'SCC',
                'contact_person' => 'Eleanor Webb',
                'email' => 'eleanor.webb@scc.example',
                'phone' => '+44-555-100-0049',
                'website' => 'https://www.scc.com',
                'address_line_1' => '120 Technology Way',
                'address_line_2' => null,
                'city' => 'Birmingham',
                'state' => null,
                'postal_code' => 'B37 7YN',
                'country' => 'United Kingdom',
                'is_active' => true,
            ],
            [
                'name' => 'Presidio',
                'contact_person' => 'Victoria Perry',
                'email' => 'victoria.perry@presidio.example',
                'phone' => '+1-555-100-0050',
                'website' => 'https://www.presidio.com',

                'address_line_2' => 'Floor 5',
                'city' => 'New York',
                'state' => 'NY',
                'postal_code' => '10022',
                'country' => 'USA',
                'is_active' => true,
            ],
            [
                'name' => 'World Wide Technology',
                'contact_person' => 'Brandon Lewis',
                'email' => 'brandon.lewis@wwt.example',
                'phone' => '+1-555-100-0051',
                'website' => 'https://www.wwt.com',

                'address_line_2' => null,
                'city' => 'Maryland Heights',
                'state' => 'MO',
                'postal_code' => '63043',
                'country' => 'USA',
                'is_active' => true,
            ],
            [
                'name' => 'Logicalis',
                'contact_person' => 'Sophie Clarke',
                'email' => 'sophie.clarke@logicalis.example',
                'phone' => '+44-555-100-0052',
                'website' => 'https://www.logicalis.com',

                'address_line_2' => 'Unit 52',
                'city' => 'Slough',
                'state' => null,
                'postal_code' => 'SL1 1YP',
                'country' => 'United Kingdom',
                'is_active' => true,
            ],
            [
                'name' => 'QBS Software',
                'contact_person' => 'William Hayes',
                'email' => 'william.hayes@qbssoftware.example',
                'phone' => '+44-555-100-0053',
                'website' => 'https://www.qbssoftware.com',

                'address_line_2' => null,
                'city' => 'London',
                'state' => null,
                'postal_code' => 'EC2A 4NE',
                'country' => 'United Kingdom',
                'is_active' => true,
            ],
            [
                'name' => 'Atea',
                'contact_person' => 'Mikkel Larsen',
                'email' => 'mikkel.larsen@atea.example',
                'phone' => '+47-555-100-0054',
                'website' => 'https://www.atea.com',

                'address_line_2' => 'Suite 554',
                'city' => 'Oslo',
                'state' => null,
                'postal_code' => '0213',
                'country' => 'Norway',
                'is_active' => true,
            ],
            [
                'name' => 'Advania',
                'contact_person' => 'Erik Johansson',
                'email' => 'erik.johansson@advania.example',
                'phone' => '+46-555-100-0055',
                'website' => 'https://www.advania.com',

                'address_line_2' => null,
                'city' => 'Stockholm',
                'state' => null,
                'postal_code' => '111 22',
                'country' => 'Sweden',
                'is_active' => true,
            ],
            [
                'name' => 'Bytes Technology Group',
                'contact_person' => 'Thabo Nkosi',
                'email' => 'thabo.nkosi@bytes.example',
                'phone' => '+27-555-100-0056',
                'website' => 'https://www.bytesplc.com',

                'address_line_2' => 'Suite 556',
                'city' => 'Johannesburg',
                'state' => 'Gauteng',
                'postal_code' => '2191',
                'country' => 'South Africa',
                'is_active' => true,
            ],
            [
                'name' => 'Proline Distribution',
                'contact_person' => 'Aisha Patel',
                'email' => 'aisha.patel@proline.example',
                'phone' => '+27-555-100-0057',
                'website' => 'https://www.proline.co.za',

                'address_line_2' => null,
                'city' => 'Johannesburg',
                'state' => 'Gauteng',
                'postal_code' => '2000',
                'country' => 'South Africa',
                'is_active' => true,
            ],
            [
                'name' => 'Mustek',
                'contact_person' => 'Pieter van der Merwe',
                'email' => 'pieter.vandermerwe@mustek.example',
                'phone' => '+27-555-100-0058',
                'website' => 'https://www.mustek.co.za',

                'address_line_2' => 'Building 58',
                'city' => 'Midrand',
                'state' => 'Gauteng',
                'postal_code' => '1685',
                'country' => 'South Africa',
                'is_active' => true,
            ],
            [
                'name' => 'Rectron',
                'contact_person' => 'Naledi Molefe',
                'email' => 'naledi.molefe@rectron.example',
                'phone' => '+27-555-100-0059',
                'website' => 'https://www.rectron.co.za',

                'address_line_2' => null,
                'city' => 'Midrand',
                'state' => 'Gauteng',
                'postal_code' => '1685',
                'country' => 'South Africa',
                'is_active' => true,
            ],
            [
                'name' => 'Comztek',
                'contact_person' => 'Lebo Dlamini',
                'email' => 'lebo.dlamini@comztek.example',
                'phone' => '+27-555-100-0060',
                'website' => 'https://www.comztek.com',

                'address_line_2' => 'Suite 660',
                'city' => 'Johannesburg',
                'state' => 'Gauteng',
                'postal_code' => '2196',
                'country' => 'South Africa',
                'is_active' => true,
            ],
        ];

        foreach($suppliers as $supplier) {
            Supplier::updateOrCreate(
                ['name' => $supplier['name']],  
                $supplier + [
                    'tax_number' => $this->taxNumberForCountry($supplier['country']),
                ]
            );
        }   
    }

    # Generate a random string of digits with the specified length
    private function randomDigits(int $length): string
    {
        $value = '';

        for ($i = 0; $i < $length; $i++) {
            $value .= (string) random_int(0, 9);
        }

        return $value;
    }

    # Generate a random string of uppercase letters with the specified length
    private function randomLetters(int $length): string
    {
        $letters = '';

        for ($i = 0; $i < $length; $i++) {
            $letters .= chr(random_int(65, 90));
        }

        return $letters;
    }

    # Generate a tax number based on the country format
    private function taxNumberForCountry(string $country): string
    {
        return match ($country) {
            'USA' => $this->randomDigits(2) . '-' . $this->randomDigits(7),

            'United Kingdom' => 'GB' . $this->randomDigits(9),

            'Canada' => $this->randomDigits(9) . 'RT0001',

            'India' => $this->randomDigits(2)
                . $this->randomLetters(5)
                . $this->randomDigits(4)
                . $this->randomLetters(1)
                . $this->randomDigits(1)
                . 'Z'
                . $this->randomDigits(1),

            'Australia' => $this->randomDigits(2) . ' '
                . $this->randomDigits(3) . ' '
                . $this->randomDigits(3) . ' '
                . $this->randomDigits(3),

            'Germany' => 'DE' . $this->randomDigits(9),

            'France' => 'FR' . $this->randomDigits(11),

            'Italy' => 'IT' . $this->randomDigits(11),

            'Switzerland' => 'CHE-' . $this->randomDigits(3) . '.'
                . $this->randomDigits(3) . '.'
                . $this->randomDigits(3),

            'South Africa' => '4' . $this->randomDigits(9),

            'Singapore' => 'M' . $this->randomDigits(8) . $this->randomLetters(1),

            'Hong Kong' => $this->randomDigits(8) . '-000-01-24-1',

            'Norway' => $this->randomDigits(9) . 'MVA',

            'Sweden' => 'SE' . $this->randomDigits(10) . '01',

            'Poland' => $this->randomDigits(10),

            'Cyprus' => 'CY' . $this->randomDigits(8) . $this->randomLetters(1),

            'Latvia' => 'LV' . $this->randomDigits(11),

            'Ireland' => 'IE' . $this->randomDigits(7) . $this->randomLetters(2),

            default => 'TX-' . strtoupper(substr(md5($country . random_int(1000, 9999)), 0, 10)),
        };
    }
}
