<?php

namespace Database\Seeders;

use App\Models\Supplier;
use Illuminate\Database\Seeder;

class SupplierSeeder extends Seeder
{
    public function run(): void
    {
        $suppliers = [
            [
                'supplier_code' => 'INGRAM',
                'name' => 'Ingram Micro',
                'contact_person' => 'Account Manager',
                'email' => 'sales@ingrammicro.local',
                'phone' => '800-555-1001',
                'address' => 'Buffalo, NY',
                'default_lead_time_days' => 5,
                'rating' => 4.65,
                'is_active' => true,
            ],
            [
                'supplier_code' => 'SYNNEX',
                'name' => 'TD Synnex',
                'contact_person' => 'Channel Partner Rep',
                'email' => 'orders@tdsynnex.local',
                'phone' => '800-555-1002',
                'address' => 'Fremont, CA',
                'default_lead_time_days' => 4,
                'rating' => 4.72,
                'is_active' => true,
            ],
            [
                'supplier_code' => 'DANDH',
                'name' => 'D&H Distributing',
                'contact_person' => 'Partner Desk',
                'email' => 'partners@dandh.local',
                'phone' => '800-555-1003',
                'address' => 'Harrisburg, PA',
                'default_lead_time_days' => 6,
                'rating' => 4.41,
                'is_active' => true,
            ],
            [
                'supplier_code' => 'ASI',
                'name' => 'ASI Corp',
                'contact_person' => 'Wholesale Sales',
                'email' => 'wholesale@asi.local',
                'phone' => '800-555-1004',
                'address' => 'Fremont, CA',
                'default_lead_time_days' => 7,
                'rating' => 4.23,
                'is_active' => true,
            ],
            [
                'supplier_code' => 'PETRA',
                'name' => 'Petra Industries',
                'contact_person' => 'Regional Rep',
                'email' => 'b2b@petra.local',
                'phone' => '800-555-1005',
                'address' => 'Edmond, OK',
                'default_lead_time_days' => 5,
                'rating' => 4.37,
                'is_active' => true,
            ],
            [
                'supplier_code' => 'TECHDATA',
                'name' => 'Tech Data Legacy',
                'contact_person' => 'Enterprise Desk',
                'email' => 'enterprise@techdata.local',
                'phone' => '800-555-1006',
                'address' => 'Clearwater, FL',
                'default_lead_time_days' => 6,
                'rating' => 4.18,
                'is_active' => false,
            ],
            [
                'supplier_code' => 'ARROW',
                'name' => 'Arrow Electronics',
                'contact_person' => 'Distribution Manager',
                'email' => 'orders@arrow.local',
                'phone' => '800-555-1007',
                'address' => 'Centennial, CO',
                'default_lead_time_days' => 8,
                'rating' => 4.29,
                'is_active' => true,
            ],
            [
                'supplier_code' => 'AVNET',
                'name' => 'Avnet Technology Solutions',
                'contact_person' => 'Account Executive',
                'email' => 'sales@avnet.local',
                'phone' => '800-555-1008',
                'address' => 'Phoenix, AZ',
                'default_lead_time_days' => 7,
                'rating' => 4.22,
                'is_active' => true,
            ],
            [
                'supplier_code' => 'EXERTIS',
                'name' => 'Exertis North America',
                'contact_person' => 'Regional Account Lead',
                'email' => 'channel@exertis.local',
                'phone' => '800-555-1009',
                'address' => 'Jamul, CA',
                'default_lead_time_days' => 6,
                'rating' => 4.11,
                'is_active' => true,
            ],
            [
                'supplier_code' => 'MALABAR',
                'name' => 'Malabar Supply Group',
                'contact_person' => 'Wholesale Rep',
                'email' => 'trade@malabar.local',
                'phone' => '800-555-1010',
                'address' => 'Dallas, TX',
                'default_lead_time_days' => 9,
                'rating' => 4.05,
                'is_active' => true,
            ],
            [
                'supplier_code' => 'BYTEWAVE',
                'name' => 'ByteWave Distribution',
                'contact_person' => 'Partner Success Lead',
                'email' => 'partners@bytewave.local',
                'phone' => '800-555-1011',
                'address' => 'Austin, TX',
                'default_lead_time_days' => 5,
                'rating' => 4.33,
                'is_active' => true,
            ],
            [
                'supplier_code' => 'REDROCK',
                'name' => 'RedRock Components',
                'contact_person' => 'Reseller Desk',
                'email' => 'resellers@redrock.local',
                'phone' => '800-555-1012',
                'address' => 'Denver, CO',
                'default_lead_time_days' => 7,
                'rating' => 4.14,
                'is_active' => true,
            ],
            [
                'supplier_code' => 'BLUECHIP',
                'name' => 'BlueChip Wholesale',
                'contact_person' => 'Procurement Contact',
                'email' => 'procurement@bluechip.local',
                'phone' => '800-555-1013',
                'address' => 'Chicago, IL',
                'default_lead_time_days' => 6,
                'rating' => 4.27,
                'is_active' => true,
            ],
            [
                'supplier_code' => 'CORELINK',
                'name' => 'CoreLink Tech Supply',
                'contact_person' => 'Inside Sales',
                'email' => 'inside@corelink.local',
                'phone' => '800-555-1014',
                'address' => 'Atlanta, GA',
                'default_lead_time_days' => 8,
                'rating' => 4.09,
                'is_active' => true,
            ],
            [
                'supplier_code' => 'NEXGEN',
                'name' => 'NexGen Hardware Partners',
                'contact_person' => 'Hardware Channel Rep',
                'email' => 'hardware@nexgen.local',
                'phone' => '800-555-1015',
                'address' => 'San Jose, CA',
                'default_lead_time_days' => 5,
                'rating' => 4.36,
                'is_active' => true,
            ],
            [
                'supplier_code' => 'PRIMEIT',
                'name' => 'Prime IT Distribution',
                'contact_person' => 'Channel Operations',
                'email' => 'ops@primeit.local',
                'phone' => '800-555-1016',
                'address' => 'Orlando, FL',
                'default_lead_time_days' => 7,
                'rating' => 4.16,
                'is_active' => true,
            ],
            [
                'supplier_code' => 'MIDWEST',
                'name' => 'Midwest Computer Supply',
                'contact_person' => 'Regional Sales Rep',
                'email' => 'regional@midwest.local',
                'phone' => '800-555-1017',
                'address' => 'Kansas City, MO',
                'default_lead_time_days' => 4,
                'rating' => 4.31,
                'is_active' => true,
            ],
            [
                'supplier_code' => 'SUNBELT',
                'name' => 'Sunbelt Device Distributors',
                'contact_person' => 'Account Support',
                'email' => 'support@sunbelt.local',
                'phone' => '800-555-1018',
                'address' => 'Phoenix, AZ',
                'default_lead_time_days' => 6,
                'rating' => 4.12,
                'is_active' => true,
            ],
            [
                'supplier_code' => 'EVEREST',
                'name' => 'Everest Systems Wholesale',
                'contact_person' => 'Territory Manager',
                'email' => 'territory@everest.local',
                'phone' => '800-555-1019',
                'address' => 'Seattle, WA',
                'default_lead_time_days' => 9,
                'rating' => 4.08,
                'is_active' => true,
            ],
            [
                'supplier_code' => 'PIONEER',
                'name' => 'Pioneer Tech Wholesale',
                'contact_person' => 'Procurement Specialist',
                'email' => 'buyers@pioneer.local',
                'phone' => '800-555-1020',
                'address' => 'Salt Lake City, UT',
                'default_lead_time_days' => 5,
                'rating' => 4.26,
                'is_active' => true,
            ],
        ];

        foreach ($suppliers as $supplier) {
            Supplier::updateOrCreate(
                ['supplier_code' => $supplier['supplier_code']],
                $supplier
            );
        }
    }
}